# General parameters
dataset: Dialysis
model_name: DeepGBM # LinearModel, KNN, SVM, DecisionTree, RandomForest, MLP
                           # XGBoost, CatBoost, LightGBM,
                           # TabNet, VIME, TabTransformer, ModelTree, NODE, DeepGBM, RLN, DNFNet,
                           # STG, NAM, DeepFM, SAINT
objective: regression
optimize_hyperparameters: True

# GPU parameters
use_gpu: False
gpu_ids: [0]
data_parallel: True

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221

# Preprocessing parameters
scale: True
target_encode: False

# Training parameters
batch_size: 2
val_batch_size: 2
early_stopping_rounds: 20
epochs: 100
logging_period: 100

# About the data
num_features: 10
num_classes: 1 # always one for regression!

# Data Augmentation
# regression_aug: True
