# General parameters
dataset: Dialysis
model_name: DeepGBM # LinearModel, KNN, SVM, DecisionTree, RandomForest, MLP
                           # XGBoost, CatBoost, LightGBM,
                           # TabNet, VIME, TabTransformer, ModelTree, NODE, DeepGBM, RLN, DNFNet,
                           # STG, NAM, DeepFM, SAINT
objective: regression
optimize_hyperparameters: True

data_path: /content/Dialysis_TabSurvey/data/df_imputed_all.csv

# GPU parameters
use_gpu: False
gpu_ids: [0]
data_parallel: True

# Optuna parameters - https://optuna.org/
n_trials: 100
direction: minimize

# Cross validation parameters
num_splits: 5
shuffle: True
seed: 221

# Preprocessing parameters
scale: True
target_encode: False

# Training parameters
batch_size: 16
data_shuffle: False # time series data should not be shuffled
val_batch_size: 8
early_stopping_rounds: 20
epochs: 500
logging_period: 100

# About the data
num_features: 0 # will be set automatically 22 or 4 depending on the use_absorbance_only argument
use_absorbance_only: False
target_variable: BUN
num_classes: 1 # always one for regression!

# Data Augmentation
regression_aug: True


